# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GHFollowers' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '13.5'

  use_frameworks!
  # Pods for GHFollowers


  target 'GHFollowersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GHFollowersUITests' do
    # Pods for testing
  end

end
